project:
  type: website
  output-dir: docs

website:
  title: "TDDR Center"
  navbar:
    left:
      - text: Home
        href: main_page.qmd
      - text: Events
        href: events.qmd
      - text: News
        href: news.qmd

format:
  html:
    theme:
      - spacelab
      - custom.scss
    toc: true

editor: visual

execute:
  freeze: auto
