project:
  type: website

website:
  title: "TDDR"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: main_page.qmd
      - text: "Events"
        href: talks.qmd
      - text: "News"
        href: about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

