project:
  type: website
  output-dir: docs

website:
  title: "TDDR Center"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Personnel
        href: personnel.qmd
      - text: Scientific Cores
        href: cores.qmd
      - text: Events
        href: events.qmd
      - text: News
        href: news.qmd
      - text: Pilots
        href: pilots.qmd
      - text: Publications
        href: publications.qmd
      - text: Grants
        href: grants.qmd
      - text: Gifts
        href: gifts.qmd

format:
  html:
    theme:
      - spacelab
      - custom.scss
    toc: true

editor: visual

execute:
  freeze: auto
